# Generated by Django 4.2.7 on 2026-03-17 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheColocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religion (optionnel)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(verbose_name='Description de la recherche')),
                ('est_active', models.BooleanField(default=True, verbose_name='Recherche active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('locataire', models.ForeignKey(limit_choices_to={'role__in': ['locataire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='recherches_colocataire', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_colocataire', to='unites.unite', verbose_name='Unité concernée')),
            ],
            options={
                'verbose_name': 'Recherche de colocataire',
                'verbose_name_plural': 'Recherches de colocataires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureColocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religion (optionnel)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(verbose_name='Description')),
                ('est_acceptee', models.BooleanField(default=False, verbose_name='Acceptée')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('candidat', models.ForeignKey(limit_choices_to={'role__in': ['locataire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_colocataire', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='colocataires.recherchecolocataire', verbose_name='Recherche associée')),
            ],
            options={
                'verbose_name': 'Candidature colocataire',
                'verbose_name_plural': 'Candidatures colocataires',
                'ordering': ['-date_candidature'],
            },
        ),
    ]
