# Generated by Django 6.0.3 on 2026-05-21 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unites', '0003_unite_date_debut_location_unite_locataire_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheColocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('annulee', 'Annulée'), ('expiree', 'Expirée'), ('terminee', 'Terminée (après paiement)')], default='active', max_length=20, verbose_name='Statut')),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religion (optionnel)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('locataire', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='recherches_colocataire', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_colocataire', to='unites.unite', verbose_name='Unité concernée')),
            ],
            options={
                'verbose_name': 'Recherche de colocataire',
                'verbose_name_plural': 'Recherches de colocataires',
                'ordering': ['-date_creation'],
                'unique_together': {('locataire', 'unite', 'statut')},
            },
        ),
        migrations.CreateModel(
            name='CandidatureColocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religion (optionnel)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_colocataire', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='colocataires.recherchecolocataire', verbose_name='Recherche associée')),
            ],
            options={
                'verbose_name': 'Candidature colocataire',
                'verbose_name_plural': 'Candidatures colocataires',
                'ordering': ['-date_candidature'],
                'unique_together': {('recherche', 'candidat')},
            },
        ),
    ]
