# Generated by Django 6.0.3 on 2026-03-18 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colocataires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaturecolocataire',
            name='candidat',
            field=models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_colocataire', to=settings.AUTH_USER_MODEL, verbose_name='Candidat'),
        ),
        migrations.AlterField(
            model_name='recherchecolocataire',
            name='locataire',
            field=models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='recherches_colocataire', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
    ]
