# Generated by Django 4.2.7 on 2026-03-17 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('unites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('avance', "Paiement d'avance (entrée)"), ('loyer', 'Paiement de loyer mensuel')], max_length=20, verbose_name='Type de paiement')),
                ('mode_paiement', models.CharField(choices=[('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('celtis', 'Celtis'), ('especes', 'Espèces')], max_length=20, verbose_name='Mode de paiement')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('numero_paiement', models.CharField(max_length=50, verbose_name='Numéro de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='locations.demandeunite', verbose_name='Demande associée')),
                ('locataire', models.ForeignKey(limit_choices_to={'role__in': ['locataire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('proprietaire', models.ForeignKey(limit_choices_to={'role__in': ['proprietaire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='unites.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('contenu', models.TextField(verbose_name='Contenu du reçu')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='recus/', verbose_name='Fichier PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.paiement', verbose_name='Paiement associé')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
            },
        ),
    ]
