# Generated by Django 6.0.3 on 2026-03-18 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='locataire',
            field=models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
    ]
