# Generated by Django 6.0.3 on 2026-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_alter_paiement_locataire_alter_paiement_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation (espèces)'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
