# Generated by Django 6.0.3 on 2026-07-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_alter_paiement_statut'),
        ('unites', '0003_unite_date_debut_location_unite_locataire_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Commission prélevée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_locataire', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.paiement', verbose_name='Paiement associé')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unites.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Journal de transaction',
                'verbose_name_plural': 'Journaux de transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
