# Generated by Django 6.0.3 on 2026-07-01 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_recuretrait_transactionjournal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recuretrait',
            options={'ordering': ['-date_generation'], 'verbose_name': 'Reçu de retrait', 'verbose_name_plural': 'Reçus de retrait'},
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de génération'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recus_retrait/', verbose_name='Fichier PDF'),
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant retiré (FCFA)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='operateur',
            field=models.CharField(choices=[('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('celtis', 'Celtis')], default=0, max_length=10, verbose_name='Opérateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='proprietaire',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='recus_retrait', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='reference',
            field=models.CharField(default='default_ref', max_length=100, unique=True, verbose_name='Référence FedaPay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuretrait',
            name='telephone',
            field=models.CharField(default='00000000', max_length=20, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
