# Generated by Django 6.0.3 on 2026-07-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_alter_recuretrait_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message du locataire')),
                ('montant_demande', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant demandé')),
                ('montant_approuve', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Montant approuvé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('locataire', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_remboursement', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(limit_choices_to={'type_paiement': 'avance'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_remboursement', to='paiements.paiement')),
                ('proprietaire', models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_remboursement_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de remboursement',
                'verbose_name_plural': 'Demandes de remboursement',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant remboursé')),
                ('date_remboursement', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('effectue', 'Effectué')], default='effectue', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='remboursements/')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remboursement', to='paiements.demanderemboursement')),
            ],
        ),
    ]
