# Generated by Django 6.0.3 on 2026-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Nouveau message'), ('demande', "Nouvelle demande d'unité"), ('reponse_demande', 'Réponse à une demande'), ('paiement', 'Paiement reçu'), ('colocataire', 'Candidature colocataire'), ('systeme', 'Information système'), ('demande_remboursement', 'Demande de remboursement'), ('remboursement_approuve', 'Remboursement approuvé'), ('remboursement_retire', 'Remboursement retiré')], max_length=25, verbose_name='Type de notification'),
        ),
    ]
