# Generated by Django 4.2.7 on 2026-03-17 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'unité")),
                ('type_unite', models.CharField(choices=[('appartement', 'Appartement'), ('boutique', 'Boutique'), ('chambre_salon_sanitaire', 'Chambre salon sanitaire'), ('chambre_salon_ordinaire', 'Chambre salon ordinaire'), ('deux_chambres_sanitaire', 'Deux chambres salon sanitaire'), ('deux_chambres_ordinaire', 'Deux chambres salon ordinaire'), ('entree_coucher_sanitaire', 'Entrée coucher sanitaire'), ('entree_coucher_ordinaire', 'Entrée coucher ordinaire')], max_length=50, verbose_name="Type d'unité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('type_douche', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='interne', max_length=20, verbose_name='Type de douche')),
                ('prepaye', models.BooleanField(default=False, help_text="Cocher si l'unité dispose d'un système prépayé", verbose_name='Avec prépayé')),
                ('garage', models.BooleanField(default=False, help_text='Disponible uniquement pour les appartements', verbose_name='Garage')),
                ('loyer', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Loyer mensuel (FCFA)')),
                ('nombre_avances', models.IntegerField(default=3, verbose_name="Nombre d'avances (mois)")),
                ('type_caution', models.CharField(choices=[('eau_seule', 'Caution eau seule'), ('electricite_seule', "Caution d'électricité seule"), ('eau_et_electricite', 'Caution eau et électricité')], max_length=30, verbose_name='Type de caution')),
                ('prix_caution', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant de la caution (FCFA)')),
                ('contact_proprietaire', models.CharField(max_length=20, verbose_name='Téléphone du propriétaire')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('maintenance', 'En maintenance')], default='libre', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unites/', verbose_name='Photo')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='unites.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
    ]
