# Generated by Django 6.0.3 on 2026-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='prepaye',
            field=models.BooleanField(default=False, verbose_name='Avec prépayé'),
        ),
    ]
