# Generated by Django 6.0.3 on 2026-03-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unites', '0002_alter_unite_garage_alter_unite_prepaye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='date_debut_location',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début de location'),
        ),
        migrations.AddField(
            model_name='unite',
            name='locataire_actuel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'locataire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_occupees', to=settings.AUTH_USER_MODEL, verbose_name='Locataire actuel'),
        ),
    ]
