# Generated by Django 6.0.3 on 2026-03-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
        ('unites', '0002_alter_unite_garage_alter_unite_prepaye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-date_dernier_message'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='unites.unite', verbose_name='Unité concernée (optionnel)'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='date_dernier_message',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
