# Generated by Django 6.0.3 on 2026-04-10 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_alter_conversation_options_conversation_unite_and_more'),
        ('unites', '0003_unite_date_debut_location_unite_locataire_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('unite',), name='unique_conversation_par_unite'),
        ),
    ]
