# Generated by Django 6.0.2 on 2026-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_role_alter_utilisateur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Locataire', 'Locataire'), ('Proprietaire', 'Propriétaire')], default='Locataire', max_length=20),
        ),
    ]
