# Generated by Django 6.0.2 on 2026-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
