# Generated by Django 6.0.2 on 2026-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateur_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
