# Generated by Django 4.2.7 on 2026-03-17 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True)),
                ('locataire', models.ForeignKey(limit_choices_to={'role__in': ['locataire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ia', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-date_dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='RecommandationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteres_recherche', models.TextField(verbose_name='Critères de recherche')),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='agent_ia.conversationia', verbose_name='Conversation')),
                ('unites', models.ManyToManyField(related_name='recommandations_ia', to='unites.unite', verbose_name='Unités recommandées')),
            ],
            options={
                'verbose_name': 'Recommandation IA',
                'verbose_name_plural': 'Recommandations IA',
            },
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_expediteur', models.CharField(choices=[('locataire', 'Locataire'), ('ia', 'Agent IA Loya')], max_length=20, verbose_name='Expéditeur')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('vocal', 'Vocal')], default='texte', max_length=20, verbose_name='Type de message')),
                ('fichier_vocal', models.FileField(blank=True, null=True, upload_to='messages_vocaux/', verbose_name='Fichier vocal')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_ia.conversationia', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'ordering': ['date_envoi'],
            },
        ),
    ]
