# Generated by Django 6.0.3 on 2026-05-16 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_ia', '0002_alter_conversationia_locataire'),
        ('unites', '0003_unite_date_debut_location_unite_locataire_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommandationia',
            options={'ordering': ['-date_recommandation'], 'verbose_name': 'Recommandation IA', 'verbose_name_plural': 'Recommandations IA'},
        ),
        migrations.AlterField(
            model_name='conversationia',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='conversationia',
            name='date_dernier_message',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Dernier message'),
        ),
        migrations.AlterField(
            model_name='conversationia',
            name='est_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='conversationia',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ia', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='messageia',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='messageia',
            name='type_expediteur',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('ia', 'Agent IA Loya')], db_index=True, max_length=20, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='recommandationia',
            name='criteres_recherche',
            field=models.JSONField(help_text="Ex: {'type': 'chambre_salon', 'budget': 15000, 'sanitaire': 'sanitaire'}", verbose_name='Critères de recherche'),
        ),
        migrations.AlterField(
            model_name='recommandationia',
            name='date_recommandation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='recommandationia',
            name='unites',
            field=models.ManyToManyField(blank=True, related_name='recommandations_ia', to='unites.unite', verbose_name='Unités recommandées'),
        ),
        migrations.AddIndex(
            model_name='messageia',
            index=models.Index(fields=['conversation', 'date_envoi'], name='idx_message_conv_date'),
        ),
        migrations.AddIndex(
            model_name='messageia',
            index=models.Index(fields=['conversation', 'id'], name='idx_message_conv_id'),
        ),
    ]
