# Generated by Django 4.2.7 on 2026-03-17 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0001_initial'),
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='mode_paiement',
            field=models.CharField(choices=[('en_ligne', 'Paiement en ligne'), ('especes', 'Espèces (ajout manuel)')], default='en_ligne', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to='proprietes.propriete', verbose_name='Propriété'),
        ),
    ]
