# Generated by Django 6.0.3 on 2026-03-18 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0002_locataire_mode_paiement_locataire_propriete'),
        ('unites', '0002_alter_unite_garage_alter_unite_prepaye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locataire',
            options={'ordering': ['-date_entree'], 'verbose_name': 'Locataire', 'verbose_name_plural': 'Locataires'},
        ),
        migrations.AlterField(
            model_name='locataire',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires_occupants', to='unites.unite', verbose_name='Unité louée'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_locataire', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
