# Generated by Django 6.0.3 on 2026-04-22 10:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0003_alter_locataire_options_alter_locataire_unite_and_more'),
        ('proprietes', '0004_alter_propriete_options_and_more'),
        ('unites', '0003_unite_date_debut_location_unite_locataire_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Locataire actif'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='date_entree',
            field=models.DateField(default=datetime.date(2026, 4, 22), verbose_name="Date d'entrée"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locataire',
            name='propriete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to='proprietes.propriete', verbose_name='Propriété'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locataire',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to='unites.unite', verbose_name='Unité louée'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='utilisateur',
            field=models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='locataire',
            unique_together={('utilisateur', 'propriete')},
        ),
    ]
