# Generated by Django 6.0.3 on 2026-04-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0005_alter_locataire_unite'),
        ('unites', '0003_unite_date_debut_location_unite_locataire_actuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='unite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataire_associe', to='unites.unite', verbose_name='Unité louée'),
        ),
    ]
