# Generated by Django 4.2.7 on 2026-03-18 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire')], default='locataire', max_length=20),
        ),
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-date_creation'],
            },
        ),
    ]
