# Generated by Django 6.0.3 on 2026-03-20 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_utilisateur_role_codeotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Token JWT')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration du token")),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navigateur/Appareil')),
                ('est_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_actives', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session active',
                'verbose_name_plural': 'Sessions actives',
                'ordering': ['-date_connexion'],
            },
        ),
    ]
