# Generated by Django 6.0.3 on 2026-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_sessionactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
