# Generated by Django 6.0.3 on 2026-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_utilisateur_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
