# Generated by Django 6.0.3 on 2026-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('utilisateur', 'token')},
        ),
    ]
