# Generated by Django 6.0.3 on 2026-04-16 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_alter_fcmtoken_token_alter_fcmtoken_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
