# Generated by Django 6.0.3 on 2026-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_alter_fcmtoken_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire'), ('non_defini', 'Non défini')], default='locataire', max_length=20),
        ),
    ]
