# Generated by Django 6.0.3 on 2026-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='description_coloc',
            field=models.TextField(blank=True, null=True, verbose_name='Description (colocation)'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='filiere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profil_colocataire_complet',
            field=models.BooleanField(default=False, verbose_name='Profil colocataire complété'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone_coloc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone (colocation)'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
