# Generated by Django 6.0.3 on 2026-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_utilisateur_description_coloc_utilisateur_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='brutal',
            field=models.BooleanField(default=False, verbose_name='Brutal'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fumeur',
            field=models.BooleanField(default=False, verbose_name='Fumeur'),
        ),
    ]
