# Generated by Django 6.0.3 on 2026-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_utilisateur_brutal_utilisateur_fumeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Solde disponible'),
        ),
    ]
