# Generated by Django 6.0.3 on 2026-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='description',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='ville',
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de la propriété'),
        ),
    ]
