# Generated by Django 6.0.3 on 2026-03-18 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0002_remove_propriete_adresse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriete',
            options={'verbose_name': 'Propriété', 'verbose_name_plural': 'Propriétés'},
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role__in': ['proprietaire']}, on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propriete',
            unique_together={('proprietaire', 'nom')},
        ),
    ]
