# Generated by Django 6.0.3 on 2026-03-18 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0003_alter_propriete_options_alter_propriete_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriete',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Propriété', 'verbose_name_plural': 'Propriétés'},
        ),
        migrations.AlterUniqueTogether(
            name='propriete',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nom',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom de la propriété'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to=settings.AUTH_USER_MODEL),
        ),
    ]
