# Generated by Django 4.2.7 on 2026-03-17 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message du locataire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('locataire', models.ForeignKey(limit_choices_to={'role__in': ['locataire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('proprietaire', models.ForeignKey(limit_choices_to={'role__in': ['proprietaire', 'les_deux']}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='unites.unite', verbose_name='Unité concernée')),
            ],
            options={
                'verbose_name': "Demande d'unité",
                'verbose_name_plural': "Demandes d'unités",
                'ordering': ['-date_demande'],
            },
        ),
    ]
