# Generated by Django 6.0.3 on 2026-03-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('unites', '0002_alter_unite_garage_alter_unite_prepaye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeunite',
            name='locataire',
            field=models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='demandeunite',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message du locataire (optionnel)'),
        ),
        migrations.AlterField(
            model_name='demandeunite',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterUniqueTogether(
            name='demandeunite',
            unique_together={('locataire', 'unite', 'statut')},
        ),
    ]
