// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeIOXxORzeAmKSWPD6UoYDJ24gIDat6M',
    appId: '1:351694266943:web:aa1123b36eb5a5d1238e8a',
    messagingSenderId: '351694266943',
    projectId: 'app-gestion-immo-benin',
    authDomain: 'app-gestion-immo-benin.firebaseapp.com',
    storageBucket: 'app-gestion-immo-benin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJlRrrmSmhFTQFPoka2HSDR9zkx3iTneo',
    appId: '1:351694266943:android:d28c4ba017d4581b238e8a',
    messagingSenderId: '351694266943',
    projectId: 'app-gestion-immo-benin',
    storageBucket: 'app-gestion-immo-benin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1zX_0XYYqUTf89eK9UWZ0MrO9yYzo1w',
    appId: '1:351694266943:ios:4eb9fcc686a69e72238e8a',
    messagingSenderId: '351694266943',
    projectId: 'app-gestion-immo-benin',
    storageBucket: 'app-gestion-immo-benin.firebasestorage.app',
    iosBundleId: 'com.example.mobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv1zX_0XYYqUTf89eK9UWZ0MrO9yYzo1w',
    appId: '1:351694266943:ios:4eb9fcc686a69e72238e8a',
    messagingSenderId: '351694266943',
    projectId: 'app-gestion-immo-benin',
    storageBucket: 'app-gestion-immo-benin.firebasestorage.app',
    iosBundleId: 'com.example.mobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACeIOXxORzeAmKSWPD6UoYDJ24gIDat6M',
    appId: '1:351694266943:web:502de9804df13295238e8a',
    messagingSenderId: '351694266943',
    projectId: 'app-gestion-immo-benin',
    authDomain: 'app-gestion-immo-benin.firebaseapp.com',
    storageBucket: 'app-gestion-immo-benin.firebasestorage.app',
  );
}
